RED = "#AC3931"
DARK_YELLOW = "#E5D352"
BRIGHT_YELLOW = "#D9E76C"
BLUE = "#537D8D"
PURPLE = "#482C3D"

BLOCK_LABEL = BLUE

VAR_TAB = BRIGHT_YELLOW
FUNC_TAB = BRIGHT_YELLOW
OBJ_TAB = BRIGHT_YELLOW

ARRAY_BG = RED

WORKSPACE_BORDER = PURPLE
